Regridded output now same dtype as input
pangeo-data/xESMF pull request #102
Opened 2021-07-16 22:04 UTC by brews

Close #99.

2021-07-16 22:16 UTC, brews commented
I think this is ready for review!

I'd especially appreciate input in how this is throwing a `ValueError` if a multi-dtype `xr.Dataset` is input.

Also, the change I needed to make to the pre-existing unit test makes me a bit nervous because this PR is clearly breaking from past behavior. Just another thing to note. Anyone else nervous about this?

2021-07-19 16:43 UTC, brews commented
I think I could use maintainer input on this. `pre-commit` is giving me some trouble. It looks like it might be a `pre-commit`/GH actions configuration issue?

Specifically, I'm looking at 
```
blackdoc.................................................................Failed
- hook id: blackdoc
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repotmc3t5mu/py_env-python3/bin/blackdoc", line 5, in <module>
    from blackdoc.__main__ import main
  File "/home/runner/.cache/pre-commit/repotmc3t5mu/py_env-python3/lib/python3.9/site-packages/blackdoc/__main__.py", line 10, in <module>
    from .blackcompat import find_project_root, gen_python_files, read_pyproject_toml
  File "/home/runner/.cache/pre-commit/repotmc3t5mu/py_env-python3/lib/python3.9/site-packages/blackdoc/blackcompat.py", line 9, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

from https://github.com/pangeo-data/xESMF/pull/102/checks?check_run_id=3091031309.

This PR hasn't added or changed dependencies.

I fixed other apparent linting issues by deactivating `pre-commit`.

2021-07-21 13:51 UTC, raphaeldussin commented
@brews please feel free to add `toml` package to the various environment yml files under `ci`
it looks like `black` does not depend on `toml` anymore but `blackdoc` does:

https://github.com/keewis/blackdoc/issues/100

this should take care of the linting test

2021-07-21 16:29 UTC, raphaeldussin requested changes
sorry, this is not necessary anymore, fixed in master

2021-07-21 16:29 UTC, brews commented
> @brews please feel free to add `toml` package to the various environment yml files under `ci`
> it looks like `black` does not depend on `toml` anymore but `blackdoc` does:
> 
> [keewis/blackdoc#100](https://github.com/keewis/blackdoc/issues/100)
> 
> this should take care of the linting test

`toml` is in the environments as of `87285ce`. This looks good to go on my end, unless CI/CD says otherwise.

2021-07-21 16:30 UTC, raphaeldussin commented
the handling in the dataset is finicky and decisions need to be made in terms of desired behavior.
the rest looks good.

2021-08-09 14:10 UTC, huard approved these changes

2021-08-12 19:12 UTC, huard commented
@raphaeldussin Could you clarify what needs to be done to merge this ? What decisions do we need to make?

2021-08-12 19:27 UTC, raphaeldussin commented
@brews I have made a PR to your branch here: https://github.com/brews/xESMF/pull/2
passing a list of different dtypes in the dataset case works fine (see test), please check and update your PR if you are satisfied with the modifications then we can move forward and merge your PR into the main code.

2021-08-12 19:29 UTC, raphaeldussin requested changes
I'd recommend updating PR with modifs from here https://github.com/brews/xESMF/pull/2

2021-08-12 21:14 UTC, brews commented on xesmf/frontend.py
> +        # Being cautious as input data might have deliberate dtype precision
I merged in your PR. I had an error when I tried something like this earlier but this clearly works not. Thanks so much. Marking as resolved.

2021-08-12 21:20 UTC, brews commented
Thanks for the bump, @huard. I merged in the suggested corrections from @raphaeldussin. I agree with @raphaeldussin that accepting multiple dtypes from Datasets is ideal behavior. It appears to work in testing so 👍 .

Pending CI/CD checks, I think this is ready for re-review, @raphaeldussin.

2021-08-12 21:43 UTC, raphaeldussin approved these changes

2021-08-12 21:43 UTC, raphaeldussin commented
LGTM

2021-08-12 21:43 UTC, merged