Reduce dask task count, refactor regrid dispatch
pangeo-data/xESMF pull request #135
Opened 2021-11-16 19:57 UTC by aulemahal

This fixes #127 and fixes #117 (maybe that one was already fixed?).

At the beginning, I tried to explore @dcherian's idea of using dask's `tensordot` directly instead of wrapping everything in a  `xr.apply_ufunc` with `dask='parallelized'`. Sadly, that didn't go as well as planned : the performance was not better, sometimes it was equal, sometimes worst. But, building on that, I moved things around to see if it could improve.  I'm a bit disappointed as this final solution is not _that_ much more performant than before...

The dask graph issue (127) is fixed explicitly by wrapping the weights into a dask array ourselves. I could have done just that, but the changes here have the following bonuses:
- Reorder the checks and the computation : shape checks are now done _before_ the computation, which means a wrongly shaped input using dask will raise an error on the line calling the regridder, instead of further down in the `load()` or `to_netcdf` call.
- The number of dasks added by the Regridder is now Nchunks + 1, no more. It's slightly better than before (master).
- It erases the fix of #122. Dask is now made aware of the output dtype outside of xarray, so dtype is preseved on dataset without additionnal code. 

Because of this rewrite and constraints given by `regrid_dataset`, it was easier to have a single `regrid_array` that handles the switch between dask and numpy arrays. That rendered `regrid_numpy` and `regrid_dask` kinda useless, so I took the decision to deprecated them. We can remove the warnings if you think this breaking change is not necessary.

## Performances
As said above, the overall performance of this branch is quite similar to the one of the master IF we set the dask config to avoid the bug of #127. In general, it reduces the number of task in the tree, but that improvement was diluted in my tests because dask is able to optimize said tree by merging tasks. Memory-wise, the two branches are quite equivalent, both are better than v0.6.0. 

## Going forward
Overall this is a lot of lines changed for a bug fix, but it opens possibilities for handling of spatial chunks. Without `dask='parallelized`, it could be possible to have a chunked output for very large grids?

I observed serious memory usage when `skipna=True`. I'm pretty sure this could be improved by merging some operations together?

Also, now that the weights are in a sparse DataArray, we could make them 4-D instead of 2D, maybe that could reduce the  `reshape` calls and improve performance?

All things to do in further PRs.

## TL;DR
Thisfixes a bug, but introduces many less important changes because it was coded incrementally.  If requested, I can redo another PR with only the bug-fixing change.

2021-11-16 20:32 UTC, huard requested changes
Minor changes.

2021-11-16 20:32 UTC, huard commented on xesmf/smm.py
> +
Docstring

2021-11-16 20:32 UTC, huard commented on xesmf/smm.py
> +    ), 'ny_out * nx_out should equal to weights.shape[0]'
replace with try/except

> Second, Python interpreter users can disable assertion statements. Therefore, a number of problems can arise if you rely on assertions too heavily for error handling and a user disables assertions.

2021-11-16 20:33 UTC, huard commented
@ScottWales Could you check this out and confirm that it works for you ?

2021-11-16 20:54 UTC, dcherian commented
>  Sadly, that didn't go as well as planned : the performance was not better, sometimes it was equal, sometimes worst.

Well the other way of looking at it is that you've enabled a major new feature (chunked spatial dimensions) without much of a performance regression 😉 

Maybe it's possible to improve tensordot for the case where there is only one chunk along spatial dimensions?

2021-11-16 20:59 UTC, aulemahal commented
AFAIK, the performance issues where not from `tensordot` itself. In my first test, I was doing everything a "duck type" manner, i.e. : all operations on `indata` in `_regrid_array` and `apply_weights` were chosen to work with numpy and dask arrays alike. This way, dask's tensordot was used, but it added many `reshape`, `transpose` and a `astype` task. I think it is this high number of very small tasks that cancelled the potential performance gain.

2021-11-22 21:41 UTC, huard approved these changes

2021-11-22 21:54 UTC, raphaeldussin approved these changes

2021-11-22 21:55 UTC, raphaeldussin commented
great job @aulemahal

2021-11-22 21:56 UTC, merged